#!/usr/bin/env python3
"""Generate tab hubs and redirect stubs for merged pages.

Two kinds of merge exist (see AGENTS.md, "Merged pages"):

* Tab hubs: one page with a tab per tool, each tool loaded in an iframe from
  its original file. The original file keeps its content and gets a small
  guard script: opened on its own, it redirects to the hub on its tab. The hub
  loads it with ``?hub=1`` so the guard lets it through.
* Redirect stubs: a page whose code moved into another page is replaced by a
  tiny HTML file that redirects to the new page and tab.

Everything here is generated. Edit HUBS or STUBS below and run:

    python3 scripts/build_hubs.py
"""

from __future__ import annotations

import html
import json
import os
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PAGE = ROOT / "page"

GUARD_ID = "hub-guard"
GENERATED = "Generated by scripts/build_hubs.py - edit the config there, not this file."

# --------------------------------------------------------------------------
# Hubs
# --------------------------------------------------------------------------
# Each tab:
#   id       hash and storage id of the tab (hub.html#id)
#   src      page path relative to page/
#   icon     Font Awesome class
#   label    {en, pt, ja}
#   desc     {en, pt, ja}, one sentence shown in the help dialog
#   unload   True to blank the iframe when leaving the tab (releases camera)
#   langKeys / themeKeys  page-specific storage keys the hub keeps in sync
#            with app_lang / app_theme (values "en|pt|ja" and "dark|light")
# fileTab: tab that receives files opened from the desktop (os-file-open).

HUBS = [
    {
        "file": "utils/docs.html",
        "slug": "utils-docs",
        "title": {"en": "Docs", "pt": "Documentos", "ja": "ドキュメント"},
        "intro": {
            "en": "Project, book and page editors. Markdown has a live preview; Notebook is plain text.",
            "pt": "Editores organizados em projeto, livro e página. Markdown tem pré-visualização; Caderno é texto simples.",
            "ja": "プロジェクト・ブック・ページで整理するエディタです。Markdown はプレビュー付き、ノートはプレーンテキストです。",
        },
        "fileTab": "markdown",
        "tabs": [
            {
                "id": "markdown",
                "src": "utils/markdown.html",
                "icon": "fa-brands fa-markdown",
                "label": {"en": "Markdown", "pt": "Markdown", "ja": "Markdown"},
                "desc": {
                    "en": "Markdown editor with edit, preview and split views, Mermaid diagrams and file open/save.",
                    "pt": "Editor Markdown com modos editar, visualizar e dividido, diagramas Mermaid e abrir/salvar arquivos.",
                    "ja": "編集・プレビュー・分割表示、Mermaid 図、ファイルの開く/保存に対応した Markdown エディタ。",
                },
            },
            {
                "id": "notebook",
                "src": "utils/notebook.html",
                "icon": "fa-solid fa-book",
                "label": {"en": "Notebook", "pt": "Caderno", "ja": "ノート"},
                "desc": {
                    "en": "Plain-text notes organized in projects, books and sheets.",
                    "pt": "Notas em texto simples organizadas em projetos, livros e folhas.",
                    "ja": "プロジェクト・ブック・シートで整理するプレーンテキストのノート。",
                },
            },
        ],
    },
    {
        "file": "utils/pdf_image_tools.html",
        "slug": "utils-pdf_image_tools",
        "title": {"en": "PDF & Image Tools", "pt": "Ferramentas de PDF e Imagem", "ja": "PDF・画像ツール"},
        "intro": {
            "en": "Convert images and edit PDFs in the browser. Files never leave your device.",
            "pt": "Converte imagens e edita PDFs no navegador. Os arquivos não saem do seu dispositivo.",
            "ja": "ブラウザ内で画像を変換し PDF を編集します。ファイルは端末の外に出ません。",
        },
        "fileTab": "pdf",
        "tabs": [
            {
                "id": "pdf",
                "src": "utils/pdf_toolbox.html",
                "icon": "fa-solid fa-file-pdf",
                "label": {"en": "PDF toolbox", "pt": "PDF", "ja": "PDF 編集"},
                "desc": {
                    "en": "Merge, split, rotate, reorder and extract PDF pages.",
                    "pt": "Junta, divide, gira, reordena e extrai páginas de PDF.",
                    "ja": "PDF ページの結合・分割・回転・並べ替え・抽出。",
                },
            },
            {
                "id": "images-pdf",
                "src": "utils/images_to_pdf.html",
                "icon": "fa-solid fa-images",
                "label": {"en": "Images → PDF", "pt": "Imagens → PDF", "ja": "画像 → PDF"},
                "desc": {
                    "en": "Order several images and save them as one PDF.",
                    "pt": "Ordena várias imagens e salva tudo num único PDF.",
                    "ja": "複数の画像を並べて 1 つの PDF に保存します。",
                },
            },
            {
                "id": "webp",
                "src": "utils/image_to_webp.html",
                "icon": "fa-solid fa-file-image",
                "label": {"en": "To WebP", "pt": "Para WebP", "ja": "WebP 変換"},
                "desc": {
                    "en": "Batch-convert images to WebP with a quality setting.",
                    "pt": "Converte imagens em lote para WebP, com ajuste de qualidade.",
                    "ja": "画質を指定して画像をまとめて WebP に変換します。",
                },
                "langKeys": ["image_to_webp_language"],
                "themeKeys": ["image_to_webp_theme"],
            },
        ],
    },
    {
        "file": "utils/code_lab.html",
        "slug": "utils-code_lab",
        "title": {"en": "Code Lab", "pt": "Laboratório de Código", "ja": "コードラボ"},
        "intro": {
            "en": "Run JavaScript offline or turn it into a flowchart.",
            "pt": "Executa JavaScript offline ou transforma o código em fluxograma.",
            "ja": "JavaScript をオフラインで実行したり、フローチャートに変換したりします。",
        },
        "tabs": [
            {
                "id": "run",
                "src": "misc/code_runner.html",
                "icon": "fa-solid fa-play",
                "label": {"en": "Runner", "pt": "Executar", "ja": "実行"},
                "desc": {
                    "en": "Run JavaScript in a sandbox with a canvas and a console.",
                    "pt": "Executa JavaScript numa sandbox com canvas e console.",
                    "ja": "キャンバスとコンソール付きのサンドボックスで JavaScript を実行します。",
                },
                "langKeys": ["code_runer_lang"],
                "themeKeys": ["code_runer_theme"],
            },
            {
                "id": "flow",
                "src": "utils/code_flow.html",
                "icon": "fa-solid fa-diagram-project",
                "label": {"en": "Flowchart", "pt": "Fluxograma", "ja": "フローチャート"},
                "desc": {
                    "en": "Turn JavaScript into a Mermaid flowchart.",
                    "pt": "Transforma JavaScript num fluxograma Mermaid.",
                    "ja": "JavaScript を Mermaid のフローチャートに変換します。",
                },
                "langKeys": ["code_flow_lang"],
            },
        ],
    },
    {
        "file": "utils/photo_editor.html",
        "slug": "utils-photo_editor",
        "title": {"en": "Photo Editor", "pt": "Editor de Fotos", "ja": "フォトエディタ"},
        "intro": {
            "en": "Layered image editors. Pro is the full version; Classic is the first, simpler one.",
            "pt": "Editores de imagem com camadas. Pro é a versão completa; Clássico é a primeira, mais simples.",
            "ja": "レイヤー対応の画像エディタです。Pro は完全版、Classic は最初のシンプル版です。",
        },
        "fileTab": "pro",
        "tabs": [
            {
                "id": "pro",
                "src": "utils/ps2.html",
                "icon": "fa-solid fa-wand-magic-sparkles",
                "label": {"en": "Pro", "pt": "Pro", "ja": "Pro"},
                "desc": {
                    "en": "Layers, selections, filters, history and file open/save.",
                    "pt": "Camadas, seleções, filtros, histórico e abrir/salvar arquivos.",
                    "ja": "レイヤー、選択、フィルター、履歴、ファイルの開く/保存。",
                },
            },
            {
                "id": "classic",
                "src": "utils/ps1.html",
                "icon": "fa-solid fa-paintbrush",
                "label": {"en": "Classic", "pt": "Clássico", "ja": "Classic"},
                "desc": {
                    "en": "The first, lighter layered canvas editor.",
                    "pt": "O primeiro editor de canvas com camadas, mais leve.",
                    "ja": "最初の軽量なレイヤーキャンバスエディタ。",
                },
            },
        ],
    },
    {
        "file": "utils/pixel_studio.html",
        "slug": "utils-pixel_studio",
        "title": {"en": "Pixel Studio", "pt": "Estúdio Pixel", "ja": "ピクセルスタジオ"},
        "intro": {
            "en": "Pixel art editors. Sprint adds layers and animation; the other two are earlier versions.",
            "pt": "Editores de pixel art. Sprint tem camadas e animação; os outros dois são versões anteriores.",
            "ja": "ピクセルアートエディタです。Sprint はレイヤーとアニメーション付き、他の 2 つは以前の版です。",
        },
        "tabs": [
            {
                "id": "sprint",
                "src": "utils/sprint.html",
                "icon": "fa-solid fa-film",
                "label": {"en": "Sprint", "pt": "Sprint", "ja": "Sprint"},
                "desc": {
                    "en": "Layered pixel animation with frames and export.",
                    "pt": "Animação em pixel com camadas, quadros e exportação.",
                    "ja": "レイヤーとフレームを使ったピクセルアニメーションと書き出し。",
                },
            },
            {
                "id": "modern",
                "src": "utils/pixel2.html",
                "icon": "fa-solid fa-table-cells",
                "label": {"en": "Modern", "pt": "Moderno", "ja": "モダン"},
                "desc": {
                    "en": "Pixel editor with image import.",
                    "pt": "Editor de pixel com importação de imagem.",
                    "ja": "画像の読み込みができるピクセルエディタ。",
                },
            },
            {
                "id": "vintage",
                "src": "utils/pixel1.html",
                "icon": "fa-solid fa-gamepad",
                "label": {"en": "Vintage", "pt": "Retrô", "ja": "レトロ"},
                "desc": {
                    "en": "Retro-styled pixel editor.",
                    "pt": "Editor de pixel com visual retrô.",
                    "ja": "レトロな見た目のピクセルエディタ。",
                },
            },
        ],
    },
    {
        "file": "utils/whiteboards.html",
        "slug": "utils-whiteboards",
        "title": {"en": "Whiteboard", "pt": "Quadro Branco", "ja": "ホワイトボード"},
        "intro": {
            "en": "Drawing boards. Main has tabs, saving and file open; the other two are alternative builds.",
            "pt": "Quadros de desenho. O principal tem abas, salvamento e abrir arquivo; os outros dois são versões alternativas.",
            "ja": "描画ボードです。メインはタブ・保存・ファイルを開く機能付き、他の 2 つは別バージョンです。",
        },
        "fileTab": "main",
        "tabs": [
            {
                "id": "main",
                "src": "utils/whiteboard.html",
                "icon": "fa-solid fa-chalkboard",
                "label": {"en": "Main", "pt": "Principal", "ja": "メイン"},
                "desc": {
                    "en": "Full whiteboard with board tabs, shapes, text, images and autosave.",
                    "pt": "Quadro completo com abas, formas, texto, imagens e salvamento automático.",
                    "ja": "ボードタブ、図形、テキスト、画像、自動保存に対応したホワイトボード。",
                },
            },
            {
                "id": "gemini",
                "src": "utils/whiteboard_google.html",
                "icon": "fa-solid fa-pen-nib",
                "label": {"en": "Gemini", "pt": "Gemini", "ja": "Gemini"},
                "desc": {
                    "en": "Alternative whiteboard built with Gemini. Nothing is saved.",
                    "pt": "Quadro alternativo feito com Gemini. Nada é salvo.",
                    "ja": "Gemini で作った別版のホワイトボード。保存されません。",
                },
            },
            {
                "id": "gpt",
                "src": "utils/whiteboard_gpt.html",
                "icon": "fa-solid fa-pencil",
                "label": {"en": "GPT", "pt": "GPT", "ja": "GPT"},
                "desc": {
                    "en": "Alternative whiteboard built with GPT. Nothing is saved.",
                    "pt": "Quadro alternativo feito com GPT. Nada é salvo.",
                    "ja": "GPT で作った別版のホワイトボード。保存されません。",
                },
            },
        ],
    },
    {
        "file": "misc/nebula_lab.html",
        "slug": "misc-nebula_lab",
        "title": {"en": "Nebula Lab", "pt": "Laboratório Nebulosa", "ja": "ネビュララボ"},
        "intro": {
            "en": "Gravity and star-link playgrounds. Nebula 2 has more physics, visual and tool options.",
            "pt": "Simulações de gravidade e ligações entre estrelas. Nebula 2 tem mais opções de física, visual e ferramentas.",
            "ja": "重力と星のリンクで遊ぶシミュレーションです。Nebula 2 は物理・表示・ツールの設定が多い版です。",
        },
        "tabs": [
            {
                "id": "nebula2",
                "src": "misc/nebula2.html",
                "icon": "fa-solid fa-atom",
                "label": {"en": "Nebula 2", "pt": "Nebula 2", "ja": "Nebula 2"},
                "desc": {
                    "en": "Advanced version with physics, visual and tool panels.",
                    "pt": "Versão avançada com painéis de física, visual e ferramentas.",
                    "ja": "物理・表示・ツールのパネルがある上級版。",
                },
                "langKeys": ["nebula2_lang"],
            },
            {
                "id": "nebula",
                "src": "misc/nebula.html",
                "icon": "fa-solid fa-star",
                "label": {"en": "Nebula", "pt": "Nebula", "ja": "Nebula"},
                "desc": {
                    "en": "The original gravity and star-link playground.",
                    "pt": "A simulação original de gravidade e ligações entre estrelas.",
                    "ja": "元の重力と星のリンクのシミュレーション。",
                },
                "langKeys": ["nebula_lang"],
            },
        ],
    },
    {
        "file": "misc/spin_lab.html",
        "slug": "misc-spin_lab",
        "title": {"en": "Spin Lab", "pt": "Laboratório Giratório", "ja": "スピンラボ"},
        "intro": {
            "en": "Balls bouncing inside a spinning hexagon, in three versions.",
            "pt": "Bolas quicando dentro de um hexágono giratório, em três versões.",
            "ja": "回転する六角形の中で跳ねるボール。3 つのバージョンがあります。",
        },
        "tabs": [
            {
                "id": "single",
                "src": "misc/spin1.html",
                "icon": "fa-solid fa-circle",
                "label": {"en": "One ball", "pt": "Uma bola", "ja": "ボール 1 個"},
                "desc": {
                    "en": "One ball, plain canvas physics.",
                    "pt": "Uma bola, física com canvas puro.",
                    "ja": "ボール 1 個、素の canvas による物理。",
                },
            },
            {
                "id": "sandbox",
                "src": "misc/spin2.html",
                "icon": "fa-solid fa-circle-nodes",
                "label": {"en": "Sandbox", "pt": "Sandbox", "ja": "サンドボックス"},
                "desc": {
                    "en": "Many balls in a physics sandbox.",
                    "pt": "Várias bolas numa sandbox de física.",
                    "ja": "たくさんのボールで遊ぶ物理サンドボックス。",
                },
            },
            {
                "id": "tuner",
                "src": "misc/spin3.html",
                "icon": "fa-solid fa-sliders",
                "label": {"en": "Tuner", "pt": "Ajustes", "ja": "調整"},
                "desc": {
                    "en": "Tune every physics parameter with sliders.",
                    "pt": "Ajusta cada parâmetro da física com controles deslizantes.",
                    "ja": "スライダーで物理パラメータを細かく調整します。",
                },
            },
        ],
    },
    {
        "file": "misc/vision_labs.html",
        "slug": "misc-vision_labs",
        "title": {"en": "Vision Labs", "pt": "Laboratórios de Visão", "ja": "ビジョンラボ"},
        "intro": {
            "en": "Webcam experiments with hand, face and pose tracking. The camera only runs on the open tab.",
            "pt": "Experimentos com webcam usando rastreamento de mãos, rosto e corpo. A câmera só fica ligada na aba aberta.",
            "ja": "手・顔・姿勢の追跡を使ったウェブカメラ実験です。カメラは開いているタブでだけ動きます。",
        },
        "tabs": [
            {
                "id": "motion",
                "src": "misc/vision_motion_lab.html",
                "icon": "fa-solid fa-person-running",
                "label": {"en": "Motion", "pt": "Movimento", "ja": "モーション"},
                "desc": {
                    "en": "Hand, pose and face tracking, plus a gesture-driven presentation mode.",
                    "pt": "Rastreamento de mãos, corpo e rosto, e um modo de apresentação por gestos.",
                    "ja": "手・姿勢・顔の追跡と、ジェスチャーで操作するプレゼンモード。",
                },
                "unload": True,
            },
            {
                "id": "gaze",
                "src": "misc/eye_gaze_control.html",
                "icon": "fa-solid fa-eye",
                "label": {"en": "Eye gaze", "pt": "Olhar", "ja": "視線"},
                "desc": {
                    "en": "Move a cursor with your eyes and type with dwell clicks.",
                    "pt": "Move um cursor com os olhos e digita parando o olhar sobre as teclas.",
                    "ja": "視線でカーソルを動かし、見つめてクリックして入力します。",
                },
                "unload": True,
                "langKeys": ["egc_lang"],
            },
            {
                "id": "plasma",
                "src": "misc/plasma_ball_lab.html",
                "icon": "fa-solid fa-bolt",
                "label": {"en": "Plasma", "pt": "Plasma", "ja": "プラズマ"},
                "desc": {
                    "en": "A plasma globe that follows your hand.",
                    "pt": "Um globo de plasma que segue a sua mão.",
                    "ja": "手の動きに反応するプラズマボール。",
                },
                "unload": True,
            },
        ],
    },
]

# Only hubs listed here are generated and have their tab pages guarded.
ENABLED_HUBS: set[str] = {
    "utils/docs.html",
    "utils/pdf_image_tools.html",
    "utils/code_lab.html",
    "utils/photo_editor.html",
    "utils/pixel_studio.html",
    "utils/whiteboards.html",
    "misc/nebula_lab.html",
    "misc/spin_lab.html",
    "misc/vision_labs.html",
}

# --------------------------------------------------------------------------
# Redirect stubs: old page (relative to page/) -> new page and tab.
# Grouped so a group is only written once its target really holds the code.
# --------------------------------------------------------------------------
STUBS = {
    "time": {
        "utils/timer.html": "utils/time_tools.html#stopwatch",
        "utils/time_diff.html": "utils/time_tools.html#diff",
        "utils/time_sum.html": "utils/time_tools.html#sum",
        "utils/age_calculator.html": "utils/time_tools.html#age",
        "utils/world_clocks.html": "utils/time_tools.html#world",
        "utils/forex_times.html": "utils/time_tools.html#forex",
    },
    "calc": {
        "utils/calculator.html": "utils/calculators.html#simple",
        "utils/band_calc.html": "utils/calculators.html#bandwidth",
        "utils/bitwise_converter.html": "utils/calculators.html#bitwise",
    },
    "dev": {
        "utils/regex_playground.html": "utils/dev_utils.html#regex",
        "utils/text_diff_studio.html": "utils/dev_utils.html#diff",
        "utils/fake_data_generator.html": "utils/dev_utils.html#fakedata",
        "utils/morse_code.html": "utils/dev_utils.html#morse",
        "utils/char_art_creator.html": "utils/dev_utils.html#charart",
        "utils/password_generator.html": "utils/dev_utils.html#password",
    },
    "todo": {
        "utils/todo.html": "utils/checklist.html#quick",
    },
    "prompt": {
        "utils/prompt_context.html": "utils/prompt_concat.html",
    },
}

ENABLED_STUBS: set[str] = {"time", "todo", "calc", "dev", "prompt"}

# Files the stubs made obsolete (page-local scripts only used by the old page).
OBSOLETE = {
    "todo": ["utils/todo.js"],
}


def rel(from_file: str, to_path: str) -> str:
    """Relative URL from page/<from_file> to page/<to_path> (keeps #hash)."""
    path, _, frag = to_path.partition("#")
    out = os.path.relpath(PAGE / path, (PAGE / from_file).parent).replace(os.sep, "/")
    return out + ("#" + frag if frag else "")


def icon_href(from_file: str, slug: str) -> str:
    return rel(from_file, f"assets/icons/ico/{slug}.ico")


def slug_of(path: str) -> str:
    parts = path[:-5].split("/")
    return "-".join(parts)


# --------------------------------------------------------------------------
# Hub page
# --------------------------------------------------------------------------

HUB_I18N = {
    "en": {"help": "Help", "theme": "Toggle theme", "close": "Close", "tools": "Tools on this page",
           "moved": "Old links to these tools open here, on the matching tab."},
    "pt": {"help": "Ajuda", "theme": "Alternar tema", "close": "Fechar", "tools": "Ferramentas desta página",
           "moved": "Links antigos dessas ferramentas abrem aqui, na aba correspondente."},
    "ja": {"help": "ヘルプ", "theme": "テーマ切替", "close": "閉じる", "tools": "このページのツール",
           "moved": "これらのツールの古いリンクはここの該当タブで開きます。"},
}

HUB_TEMPLATE = """<!DOCTYPE html>
<!-- __GENERATED__ -->
<html lang="en" data-theme="dark">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="icon" href="__FAVICON__" type="image/x-icon">
  <title>__TITLE__</title>
  <link rel="stylesheet" href="__FA__">
  <style>
    :root {
      --bg: #0f1518; --panel: #151d21; --panel-2: #1c262b; --border: #2a363c;
      --text: #e5edf0; --muted: #8b9ca3; --accent: #00a18c; --accent-ink: #ffffff;
    }
    html[data-theme="light"] {
      --bg: #f2f5f6; --panel: #ffffff; --panel-2: #eef3f4; --border: #d3dde0;
      --text: #1b2427; --muted: #5a6a70; --accent: #008f7d; --accent-ink: #ffffff;
    }
    * { box-sizing: border-box; }
    html, body { height: 100%; margin: 0; }
    body { background: var(--bg); color: var(--text); font: 14px/1.4 system-ui, -apple-system, "Segoe UI", "Noto Sans JP", sans-serif; overflow: hidden; }
    .app { display: grid; grid-template-rows: auto 1fr; height: 100%; }
    .topbar { display: flex; align-items: center; gap: 8px; height: 44px; padding: 0 8px 0 12px; background: var(--panel); border-bottom: 1px solid var(--border); min-width: 0; }
    .brand { display: flex; align-items: center; gap: 8px; font-weight: 600; font-size: 15px; white-space: nowrap; }
    .brand img { width: 18px; height: 18px; }
    .tabs { display: flex; gap: 2px; flex: 1; min-width: 0; overflow-x: auto; scrollbar-width: none; }
    .tabs::-webkit-scrollbar { display: none; }
    .tab { display: inline-flex; align-items: center; gap: 6px; height: 30px; padding: 0 10px; border: 0; border-radius: 6px; background: none; color: var(--muted); font: inherit; font-size: 13px; white-space: nowrap; cursor: pointer; }
    .tab:hover { background: var(--panel-2); color: var(--text); }
    .tab[aria-selected="true"] { background: var(--accent); color: var(--accent-ink); }
    .tabs.tight .tab { gap: 4px; padding: 0 6px; font-size: 12.5px; }
    .tabs.compact .tab:not([aria-selected="true"]) span { display: none; }
    .tab:focus-visible, .icon-btn:focus-visible, select:focus-visible { outline: 2px solid var(--accent); outline-offset: 1px; }
    .tools { display: flex; align-items: center; gap: 6px; margin-left: auto; }
    .icon-btn { display: grid; place-items: center; width: 30px; height: 30px; border: 1px solid var(--border); border-radius: 6px; background: var(--panel-2); color: var(--text); cursor: pointer; }
    .icon-btn:hover { border-color: var(--accent); color: var(--accent); }
    select { height: 30px; border: 1px solid var(--border); border-radius: 6px; background: var(--panel-2); color: var(--text); font: inherit; font-size: 13px; padding: 0 6px; }
    main { position: relative; min-height: 0; }
    main iframe { position: absolute; inset: 0; width: 100%; height: 100%; border: 0; background: var(--bg); }
    main iframe[hidden] { display: none; }
    dialog { width: min(560px, calc(100vw - 32px)); max-height: calc(100vh - 32px); padding: 0; border: 1px solid var(--border); border-radius: 10px; background: var(--panel); color: var(--text); }
    dialog::backdrop { background: rgb(0 0 0 / 45%); }
    dialog .dlg-head { display: flex; align-items: center; justify-content: space-between; padding: 10px 14px; border-bottom: 1px solid var(--border); font-weight: 600; }
    dialog .body { padding: 12px 14px 16px; overflow: auto; }
    dialog h3 { margin: 12px 0 6px; font-size: 13px; color: var(--muted); text-transform: uppercase; letter-spacing: .04em; }
    dialog ul { margin: 0; padding-left: 18px; }
    dialog li { margin: 4px 0; }
    dialog li.active b { color: var(--accent); }
    dialog p { margin: 0 0 8px; }
    .muted { color: var(--muted); font-size: 12px; }
    @media (max-width: 720px) {
      .brand span { display: none; }
      .tab span { display: none; }
    }
  </style>
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-NWZDZ906DJ"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
    gtag('config', 'G-NWZDZ906DJ');
  </script>
</head>
<body>
  <div class="app">
    <header class="topbar">
      <div class="brand"><img src="__ICON_SVG__" alt=""><span id="hub-title">__TITLE__</span></div>
      <nav class="tabs" id="tabs" role="tablist"></nav>
      <div class="tools">
        <button class="icon-btn" id="help-btn" type="button"><i class="fa-solid fa-circle-question"></i></button>
        <select id="lang-switcher" aria-label="Language">
          <option value="en">EN</option>
          <option value="pt">PT</option>
          <option value="ja">JA</option>
        </select>
        <button class="icon-btn" id="theme-switcher" type="button"><i class="fa-solid fa-moon"></i></button>
      </div>
    </header>
    <main id="frames"></main>
  </div>

  <dialog id="help">
    <div class="dlg-head"><span id="help-title"></span><button class="icon-btn" id="help-close" type="button"><i class="fa-solid fa-xmark"></i></button></div>
    <div class="body">
      <p id="help-intro"></p>
      <h3 id="help-tools"></h3>
      <ul id="help-list"></ul>
      <p class="muted" id="help-moved" style="margin-top:12px"></p>
    </div>
  </dialog>

  <script src="__EMBED__"></script>
  <script>
    (() => {
      const HUB = __CONFIG__;
      const TEXT = __TEXT__;
      const TAB_KEY = "hub:" + HUB.slug + ":tab";
      const tabsEl = document.getElementById("tabs");
      const framesEl = document.getElementById("frames");
      const langSel = document.getElementById("lang-switcher");
      const themeBtn = document.getElementById("theme-switcher");
      const help = document.getElementById("help");
      const frames = new Map();
      let active = null;

      const store = {
        get(key) { try { return localStorage.getItem(key); } catch (_) { return null; } },
        set(key, value) { try { localStorage.setItem(key, value); } catch (_) {} },
      };

      let lang = store.get("app_lang");
      if (!TEXT[lang]) lang = "en";
      let theme = store.get("app_theme") === "light" ? "light" : "dark";

      // Keep page-specific language/theme keys in step with the shared ones,
      // so every tool opens in the language and theme chosen here.
      function syncToolKeys() {
        HUB.tabs.forEach((tab) => {
          (tab.langKeys || []).forEach((key) => store.set(key, lang));
          (tab.themeKeys || []).forEach((key) => store.set(key, theme));
        });
      }

      function tabById(id) { return HUB.tabs.find((tab) => tab.id === id) || null; }

      function parseHash() {
        const raw = decodeURIComponent(location.hash.slice(1));
        const cut = raw.indexOf(":");
        const id = cut < 0 ? raw : raw.slice(0, cut);
        return { tab: tabById(id), inner: cut < 0 ? "" : raw.slice(cut + 1) };
      }

      function frameFor(tab, inner) {
        let frame = frames.get(tab.id);
        if (!frame) {
          frame = document.createElement("iframe");
          frame.title = tab.label[lang] || tab.label.en;
          frame.allow = "camera; microphone; fullscreen; clipboard-read; clipboard-write; autoplay";
          frame.dataset.tab = tab.id;
          if (window.OSEmbed) window.OSEmbed.attach(frame);
          framesEl.appendChild(frame);
          frames.set(tab.id, frame);
        }
        if (!frame.dataset.loaded) {
          frame.src = tab.src + (tab.src.includes("?") ? "&" : "?") + "hub=1" + (inner ? "#" + inner : "");
          frame.dataset.loaded = "1";
        }
        return frame;
      }

      function select(id, opts = {}) {
        const tab = tabById(id) || HUB.tabs[0];
        if (active && active !== tab.id) {
          const prev = tabById(active);
          const prevFrame = frames.get(active);
          if (prevFrame) {
            prevFrame.hidden = true;
            if (prev && prev.unload) {
              prevFrame.src = "about:blank";
              delete prevFrame.dataset.loaded;
            }
          }
        }
        active = tab.id;
        const frame = frameFor(tab, opts.inner || "");
        frame.hidden = false;
        tabsEl.querySelectorAll(".tab").forEach((btn) => {
          const on = btn.dataset.tab === tab.id;
          btn.setAttribute("aria-selected", on ? "true" : "false");
          btn.tabIndex = on ? 0 : -1;
        });
        fitTabs();
        store.set(TAB_KEY, tab.id);
        if (!opts.fromHash && location.hash.slice(1).split(":")[0] !== tab.id) {
          history.replaceState(null, "", "#" + tab.id);
        }
        renderHelp();
      }

      function renderTabs() {
        tabsEl.innerHTML = "";
        HUB.tabs.forEach((tab) => {
          const btn = document.createElement("button");
          btn.type = "button";
          btn.className = "tab";
          btn.role = "tab";
          btn.dataset.tab = tab.id;
          const label = tab.label[lang] || tab.label.en;
          btn.title = label;
          btn.innerHTML = '<i class="' + tab.icon + '" aria-hidden="true"></i><span></span>';
          btn.querySelector("span").textContent = label;
          btn.setAttribute("aria-selected", tab.id === active ? "true" : "false");
          btn.addEventListener("click", () => select(tab.id));
          tabsEl.appendChild(btn);
        });
        fitTabs();
      }

      // Show every label when they fit; otherwise only the selected tab keeps its label.
      function fitTabs() {
        tabsEl.classList.remove("tight", "compact");
        if (tabsEl.scrollWidth > tabsEl.clientWidth + 1) tabsEl.classList.add("tight");
        if (tabsEl.scrollWidth > tabsEl.clientWidth + 1) tabsEl.classList.add("compact");
      }
      new ResizeObserver(fitTabs).observe(tabsEl);
      // Icon fonts load after the first layout and widen the tabs.
      window.addEventListener("load", fitTabs);
      if (document.fonts) document.fonts.ready.then(fitTabs);

      function renderHelp() {
        const t = TEXT[lang];
        document.getElementById("help-title").textContent = HUB.title[lang] || HUB.title.en;
        document.getElementById("help-intro").textContent = HUB.intro[lang] || HUB.intro.en;
        document.getElementById("help-tools").textContent = t.tools;
        document.getElementById("help-moved").textContent = t.moved;
        const list = document.getElementById("help-list");
        list.innerHTML = "";
        HUB.tabs.forEach((tab) => {
          const li = document.createElement("li");
          if (tab.id === active) li.className = "active";
          const b = document.createElement("b");
          b.textContent = tab.label[lang] || tab.label.en;
          li.appendChild(b);
          li.appendChild(document.createTextNode(" - " + (tab.desc[lang] || tab.desc.en)));
          list.appendChild(li);
        });
      }

      function applyText() {
        const t = TEXT[lang];
        const title = HUB.title[lang] || HUB.title.en;
        document.documentElement.lang = lang;
        document.title = title;
        document.getElementById("hub-title").textContent = title;
        document.getElementById("help-btn").title = t.help;
        document.getElementById("help-btn").setAttribute("aria-label", t.help);
        document.getElementById("help-close").setAttribute("aria-label", t.close);
        themeBtn.title = t.theme;
        themeBtn.setAttribute("aria-label", t.theme);
        langSel.value = lang;
        renderTabs();
        renderHelp();
      }

      function applyTheme() {
        document.documentElement.dataset.theme = theme;
        themeBtn.querySelector("i").className = theme === "light" ? "fa-solid fa-moon" : "fa-solid fa-sun";
      }

      // Tools read language and theme on load, so reload the ones already open.
      function reloadTools() {
        frames.forEach((frame) => {
          if (!frame.dataset.loaded) return;
          try { frame.contentWindow.location.reload(); } catch (_) {}
        });
      }

      langSel.addEventListener("change", () => {
        lang = TEXT[langSel.value] ? langSel.value : "en";
        store.set("app_lang", lang);
        syncToolKeys();
        applyText();
        reloadTools();
      });

      themeBtn.addEventListener("click", () => {
        theme = theme === "light" ? "dark" : "light";
        store.set("app_theme", theme);
        syncToolKeys();
        applyTheme();
        reloadTools();
      });

      document.getElementById("help-btn").addEventListener("click", () => help.showModal());
      document.getElementById("help-close").addEventListener("click", () => help.close());
      help.addEventListener("click", (e) => { if (e.target === help) help.close(); });
      document.addEventListener("keydown", (e) => {
        if (e.key === "?" && !help.open && !/INPUT|TEXTAREA|SELECT/.test(document.activeElement.tagName)) help.showModal();
      });

      tabsEl.addEventListener("keydown", (e) => {
        if (e.key !== "ArrowRight" && e.key !== "ArrowLeft") return;
        const i = HUB.tabs.findIndex((tab) => tab.id === active);
        const next = HUB.tabs[(i + (e.key === "ArrowRight" ? 1 : -1) + HUB.tabs.length) % HUB.tabs.length];
        select(next.id);
        tabsEl.querySelector('[data-tab="' + next.id + '"]').focus();
      });

      window.addEventListener("hashchange", () => {
        const { tab, inner } = parseHash();
        if (tab && tab.id !== active) select(tab.id, { fromHash: true, inner });
      });

      // Files opened from the desktop go to the tool that edits them.
      window.addEventListener("message", (e) => {
        if (e.origin !== location.origin || !e.data) return;
        if (e.data.type !== "os-file-open" && e.data.type !== "os-sheets-open") return;
        if (e.source && Array.from(frames.values()).some((f) => f.contentWindow === e.source)) return;
        const target = tabById(HUB.fileTab) || tabById(active);
        if (!target) return;
        const wasLoaded = frames.has(target.id) && frames.get(target.id).dataset.loaded;
        select(target.id);
        // A freshly loaded tool picks up the file itself; a loaded one needs the message.
        if (wasLoaded) frames.get(target.id).contentWindow.postMessage(e.data, location.origin);
      });

      syncToolKeys();
      applyTheme();
      applyText();
      const start = parseHash();
      select((start.tab && start.tab.id) || store.get(TAB_KEY) || HUB.tabs[0].id, { inner: start.inner });
    })();
  </script>
</body>
</html>
"""


def build_hub(hub: dict) -> None:
    file = hub["file"]
    config = {
        "slug": hub["slug"],
        "title": hub["title"],
        "intro": hub["intro"],
        "fileTab": hub.get("fileTab"),
        "tabs": [
            {
                "id": t["id"],
                "src": rel(file, t["src"]),
                "icon": t["icon"],
                "label": t["label"],
                "desc": t["desc"],
                "unload": bool(t.get("unload")),
                "langKeys": t.get("langKeys", []),
                "themeKeys": t.get("themeKeys", []),
            }
            for t in hub["tabs"]
        ],
    }
    out = (
        HUB_TEMPLATE.replace("__GENERATED__", GENERATED)
        .replace("__FAVICON__", icon_href(file, hub["slug"]))
        .replace("__ICON_SVG__", rel(file, f"assets/icons/svg/{hub['slug']}.svg"))
        .replace("__FA__", rel(file, "assets/fontawesome/css/all.min.css"))
        .replace("__EMBED__", rel(file, "os/js/embed.js"))
        .replace("__TITLE__", html.escape(hub["title"]["en"]))
        .replace("__CONFIG__", json.dumps(config, ensure_ascii=False, indent=2).replace("\n", "\n      "))
        .replace("__TEXT__", json.dumps(HUB_I18N, ensure_ascii=False))
    )
    (PAGE / file).write_text(out, encoding="utf-8")
    print(f"hub    {file} ({len(hub['tabs'])} tabs)")


# --------------------------------------------------------------------------
# Guard injected into every page that lives inside a hub
# --------------------------------------------------------------------------

GUARD_RE = re.compile(r'\s*<script id="hub-guard">.*?</script>', re.S)


def guard_script(page_file: str, hub_file: str, tab_id: str) -> str:
    target = rel(page_file, hub_file)
    return (
        f'<script id="{GUARD_ID}">/* {GENERATED} */'
        "(function(){if(/[?&]hub=1(&|$)/.test(location.search)){document.documentElement.dataset.hub='1';return;}"
        f"var h=location.hash?':'+location.hash.slice(1):'';location.replace({json.dumps(target + '#' + tab_id)}+h);"
        "})();</script>"
    )


def add_guard(page_file: str, hub_file: str, tab_id: str) -> None:
    path = PAGE / page_file
    text = path.read_text(encoding="utf-8")
    text = GUARD_RE.sub("", text)
    m = re.search(r"<head[^>]*>", text, re.I)
    if not m:
        raise SystemExit(f"no <head> in {page_file}")
    text = text[: m.end()] + "\n  " + guard_script(page_file, hub_file, tab_id) + text[m.end():]
    path.write_text(text, encoding="utf-8")
    print(f"guard  {page_file} -> {hub_file}#{tab_id}")


# --------------------------------------------------------------------------
# Redirect stubs
# --------------------------------------------------------------------------

STUB_TEMPLATE = """<!DOCTYPE html>
<!-- __GENERATED__ -->
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="robots" content="noindex">
  <meta http-equiv="refresh" content="0; url=__TARGET__">
  <link rel="canonical" href="__TARGET__">
  <link rel="icon" href="__FAVICON__" type="image/x-icon">
  <title>__NAME__</title>
  <script>location.replace(__TARGET_JS__);</script>
  <style>body{font:14px system-ui,sans-serif;margin:24px;color:#1b2427;background:#f2f5f6}@media(prefers-color-scheme:dark){body{color:#e5edf0;background:#0f1518}}a{color:#00a18c}</style>
</head>
<body>
  <p>Moved to <a href="__TARGET__">__TARGET_TEXT__</a>. · Movido para <a href="__TARGET__">__TARGET_TEXT__</a>. · <a href="__TARGET__">__TARGET_TEXT__</a> に移動しました。</p>
</body>
</html>
"""


def build_stub(old: str, new: str) -> None:
    target = rel(old, new)
    new_slug = slug_of(new.split("#")[0])
    out = (
        STUB_TEMPLATE.replace("__GENERATED__", GENERATED)
        .replace("__TARGET_JS__", json.dumps(target))
        .replace("__TARGET_TEXT__", html.escape(new.split("#")[0].split("/")[-1]))
        .replace("__TARGET__", html.escape(target))
        .replace("__FAVICON__", icon_href(old, new_slug))
        .replace("__NAME__", html.escape(new.split("#")[0].split("/")[-1]))
    )
    (PAGE / old).write_text(out, encoding="utf-8")
    print(f"stub   {old} -> {new}")


def main() -> None:
    for hub in HUBS:
        if hub["file"] not in ENABLED_HUBS:
            continue
        build_hub(hub)
        for tab in hub["tabs"]:
            add_guard(tab["src"], hub["file"], tab["id"])
    for group, mapping in STUBS.items():
        if group not in ENABLED_STUBS:
            continue
        for old, new in mapping.items():
            if not (PAGE / new.split("#")[0]).exists():
                raise SystemExit(f"stub target missing: {new}")
            build_stub(old, new)
        for extra in OBSOLETE.get(group, []):
            path = PAGE / extra
            if path.exists():
                path.unlink()
                print(f"remove {extra}")


if __name__ == "__main__":
    main()
